#!/usr/bin/env ruby

if ARGV.size != 2
  puts 'Error: Wrong arguments'
  puts 'Usage: ./rectangle ${width} ${length}'
  return
end

if ARGV[0].to_i < 1 || ARGV[1].to_i < 1
  puts 'Error: ${width} and ${length} arguments must be positive integers.'
  puts 'Usage: ./rectangle ${width} ${length}'
  return
end

puts 'lol'
