#!/usr/bin/env ruby

def print_character
  print 'A'
end

if ARGV.size != 2
  puts 'Error: Wrong arguments'
  puts 'Usage: ./rectangle ${width} ${length}'
  return
end

width = ARGV[0].to_i
length = ARGV[1].to_i

if width < 1 || length < 1
  puts 'Error: ${width} and ${length} arguments must be positive integers.'
  puts 'Usage: ./rectangle ${width} ${length}'
  return
end

length.times do |line|
  width.times do |column|
    print_character
  end
  puts ''
end
